name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CREDENTIALS.ARM_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_CREDENTIALS.ARM_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CREDENTIALS.ARM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_CREDENTIALS.ARM_TENANT_ID }}


    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CREDENTIALS.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CREDENTIALS.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.ARM_TENANT_ID }}